import type { Item } from '../../shared/types'

export const MOCK_ITEMS: Item[] = [
  {
    id: '1',
    type: 'image',
    title: 'Braun T3 Pocket Radio',
    description: 'Dieter Rams, 1958. The purest expression of less but better.',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    sourceUrl: 'https://www.vitsoe.com/us/about/good-design',
    notes: 'The proportions are perfect. Every surface is necessary.',
    tags: [
      { id: 't1', name: 'industrial design', slug: 'industrial-design' },
      { id: 't2', name: 'braun', slug: 'braun' },
      { id: 't3', name: 'form follows function', slug: 'form-follows-function' },
    ],
    savedAt: '2026-02-14T10:00:00Z',
    updatedAt: '2026-02-14T10:00:00Z',
  },
  {
    id: '2',
    type: 'quote',
    content: 'Good design is as little design as possible.',
    title: 'Dieter Rams',
    tags: [
      { id: 't4', name: 'design philosophy', slug: 'design-philosophy' },
      { id: 't3', name: 'form follows function', slug: 'form-follows-function' },
    ],
    savedAt: '2026-02-15T14:30:00Z',
    updatedAt: '2026-02-15T14:30:00Z',
  },
  {
    id: '3',
    type: 'film',
    title: 'In the Mood for Love',
    description: 'Wong Kar-wai, 2000',
    imageUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800',
    notes: 'The texture of longing. Every frame a painting.',
    tags: [
      { id: 't5', name: 'slow cinema', slug: 'slow-cinema' },
      { id: 't6', name: 'hong kong', slug: 'hong-kong' },
      { id: 't7', name: 'melancholy', slug: 'melancholy' },
    ],
    savedAt: '2026-02-18T20:00:00Z',
    updatedAt: '2026-02-18T20:00:00Z',
  },
  {
    id: '4',
    type: 'image',
    title: 'Tadao Ando — Church of the Light',
    imageUrl: 'https://images.unsplash.com/photo-1470723710355-95304d8aece4?w=800',
    sourceUrl: 'https://www.archdaily.com/102149/ad-classics-church-of-the-light-tadao-ando',
    tags: [
      { id: 't8', name: 'architecture', slug: 'architecture' },
      { id: 't9', name: 'brutalism', slug: 'brutalism' },
      { id: 't10', name: 'concrete', slug: 'concrete' },
    ],
    savedAt: '2026-02-20T08:00:00Z',
    updatedAt: '2026-02-20T08:00:00Z',
  },
  {
    id: '5',
    type: 'music',
    title: 'A Winged Victory for the Sullen',
    description: 'Self-titled, 2011',
    notes: 'The sound of light entering a room slowly.',
    tags: [
      { id: 't11', name: 'ambient', slug: 'ambient' },
      { id: 't12', name: 'neo-classical', slug: 'neo-classical' },
      { id: 't7', name: 'melancholy', slug: 'melancholy' },
    ],
    savedAt: '2026-02-22T11:00:00Z',
    updatedAt: '2026-02-22T11:00:00Z',
  },
  {
    id: '6',
    type: 'link',
    title: 'The Ten Principles of Good Design — Vitsœ',
    sourceUrl: 'https://www.vitsoe.com/us/about/good-design',
    tags: [
      { id: 't4', name: 'design philosophy', slug: 'design-philosophy' },
      { id: 't2', name: 'braun', slug: 'braun' },
    ],
    savedAt: '2026-02-25T16:00:00Z',
    updatedAt: '2026-02-25T16:00:00Z',
  },
  {
    id: '7',
    type: 'image',
    title: 'Isamu Noguchi Table',
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
    notes: 'Where sculpture becomes furniture. The base as counterpoint.',
    tags: [
      { id: 't1', name: 'industrial design', slug: 'industrial-design' },
      { id: 't13', name: 'furniture', slug: 'furniture' },
      { id: 't14', name: 'japanese', slug: 'japanese' },
    ],
    savedAt: '2026-03-01T09:00:00Z',
    updatedAt: '2026-03-01T09:00:00Z',
  },
  {
    id: '8',
    type: 'place',
    title: 'Naoshima, Japan',
    imageUrl: 'https://images.unsplash.com/photo-1480796927426-f609979314bd?w=800',
    description: 'Art island off the coast of Kagawa Prefecture.',
    notes: 'The Chichu Art Museum. Buried in the earth. Light as the medium.',
    tags: [
      { id: 't14', name: 'japanese', slug: 'japanese' },
      { id: 't8', name: 'architecture', slug: 'architecture' },
      { id: 't15', name: 'to visit', slug: 'to-visit' },
    ],
    savedAt: '2026-03-05T07:00:00Z',
    updatedAt: '2026-03-05T07:00:00Z',
  },
]
